ftp:
  host: "ftp.radius.ru:8021"
  login: "GS"
  password: "GS"
  sourcePath: "PHOTO_HH_MSK"
  destinationPath: "/Users/kot/Documents/dowm"
  isRewrite: true
  logPath: "/Users/kot/Documents/dowm/log.log"